### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by privettoli** [mvmn/mvmvKafkaGUI#2]
```bash
% java -jar /Users/user/Downloads/mvmn-kafkagui-0.0.2-SNAPSHOT.jar
```
When I click `Test Connection`, the app says `Connection successful!`, then I click `Connect`, see alert `Connecting` and then Admin window again. 
```java
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at x.mvmn.kafkagui.gui.KafkaAdminGui.lambda$null$19(KafkaAdminGui.java:158)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
Environment:
```
MacBook Pro 2018 i7-8559U
Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
16 GB 2133 MHz LPDDR3
macOS Catalina 10.15.6 (19G2021)

openjdk 11.0.7 2020-04-14 HotSpot
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
Connecting to `Kafka Karafka` with `SASL_SSL` and `SCRAM-SHA-256`

**Comment by privettoli** [comment]
Resolved the problem locally by wrapping 
```java
description.authorizedOperations().stream().map(op -> op.name())
```
into
```java
ofNullable(description.authorizedOperations())
  .flatMap(Collection::stream)
  .filter(Objects::nonNull)
  .map(Enum::name)
  .forEach(opName -> aclsNode.add(new DefaultMutableTreeNode(opName, false)));
```

**Comment by mvmn** [comment]
Thank you, Anatoliy. I will incorporate the fix ASAP.

**Comment by mvmn** [comment]
https://github.com/mvmn/mvmnKafkaGUI/releases/tag/0.0.3
